---
- name: install package
  hosts: all
  become: yes

  tasks:
    - name: cheking operate system
      debug: var=ansible_os_family

    - block: # =======Block for RedHat=======
        - name: install bluetooth
          ansible.builtin.dnf:
            name:
              - pavucontrol
              - pipewire
              - bluez
            state: absent
        - name: restart demons
          ansible.builtin.systemd:
            state: started
            name: bluetooth.target
        - name: add_file_rhel
          ansible.builtin.file:
            path: /home/master/file2.txt
            state: touch
            owner: master
            group: master
            mode: 0777



      when: ansible_os_family == "RedHat"

    - block: #=====Block for debian=====
        - name: install bluetooth
          ansible.builtin.apt:
            name:
              - pavucontrol
              - bluez
              - pipewire
            state: latest
        - name: restart demon
          ansible.builtin.systemd:
            name: bluetooth.target
            state: started
        - name: reload_demons
          ansible.builtin.shell:
             systemctl --user daemon-reload
        - name: hostnamectl check
          ansible.builtin.shell:
             uname -r
          register: results
        - debug:
            var: results
        - name: add_new_file
          ansible.builtin.file:
            path: /home/master/file1.txt
            state: absent
            owner: master
            group: master
            mode: 0777


      when: ansible_os_family == "Debian"